package dev.Lovelace.EventPro.IGU;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author FBK Gamer
 */
public class LoginIGU extends javax.swing.JFrame {

  /**
   * Creates new form UXLogin
   */
  public LoginIGU() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    PanelLogin = new javax.swing.JPanel();
    etiUsuario = new javax.swing.JLabel();
    txtUsuario = new javax.swing.JTextField();
    etiContrasenia = new javax.swing.JLabel();
    txtContrasenia = new javax.swing.JPasswordField();
    etiEncabezado = new javax.swing.JLabel();
    btnIngresar = new java.awt.Button();
    btnVisibilidad = new javax.swing.JToggleButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Inicio de sesión");
    setBackground(new java.awt.Color(0, 0, 0));
    setLocation(new java.awt.Point(100, 100));
    setLocationByPlatform(true);
    setMaximumSize(new java.awt.Dimension(500, 500));
    setName("Login"); // NOI18N
    setResizable(false);

    PanelLogin.setBackground(new java.awt.Color(0, 84, 130));
    PanelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inicio de sesión", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial Black", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
    PanelLogin.setForeground(new java.awt.Color(0, 102, 102));
    PanelLogin.setPreferredSize(new java.awt.Dimension(300, 400));

    etiUsuario.setBackground(new java.awt.Color(255, 255, 255));
    etiUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    etiUsuario.setForeground(new java.awt.Color(255, 255, 255));
    etiUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    etiUsuario.setText("Usuario");
    etiUsuario.setToolTipText("");

    txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
    txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txtUsuario.setBorder(null);
    txtUsuario.setMaximumSize(new java.awt.Dimension(68, 25));
    txtUsuario.setMinimumSize(new java.awt.Dimension(68, 25));
    txtUsuario.setPreferredSize(new java.awt.Dimension(68, 25));
    txtUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtUsuarioActionPerformed(evt);
      }
    });

    etiContrasenia.setBackground(new java.awt.Color(255, 255, 255));
    etiContrasenia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    etiContrasenia.setForeground(new java.awt.Color(255, 255, 255));
    etiContrasenia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    etiContrasenia.setText("Contraseña");

    txtContrasenia.setBackground(new java.awt.Color(255, 255, 255));
    txtContrasenia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    txtContrasenia.setBorder(null);
    txtContrasenia.setMaximumSize(new java.awt.Dimension(68, 25));
    txtContrasenia.setMinimumSize(new java.awt.Dimension(68, 25));
    txtContrasenia.setName(""); // NOI18N
    txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtContraseniaActionPerformed(evt);
      }
    });

    etiEncabezado.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
    etiEncabezado.setText("Ingrese sus credenciales a continuación");
    etiEncabezado.setEnabled(false);

    btnIngresar.setActionCommand("Ingresando");
    btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    btnIngresar.setLabel("Ingresar");
    btnIngresar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnIngresarActionPerformed(evt);
      }
    });

    btnVisibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IGU/visible.png"))); // NOI18N
    btnVisibilidad.setBorder(null);
    btnVisibilidad.setPreferredSize(new java.awt.Dimension(25, 25));
    btnVisibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnVisibilidadMouseClicked(evt);
      }
    });
    btnVisibilidad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnVisibilidadActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
    PanelLogin.setLayout(PanelLoginLayout);
    PanelLoginLayout.setHorizontalGroup(
      PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
        .addContainerGap(25, Short.MAX_VALUE)
        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(etiUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(etiContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(etiEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
              .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(btnVisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addGap(25, 25, 25))
    );
    PanelLoginLayout.setVerticalGroup(
      PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(PanelLoginLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(etiEncabezado)
        .addGap(18, 18, 18)
        .addComponent(etiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(3, 3, 3)
        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(etiContrasenia)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(btnVisibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtContrasenia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(66, 66, 66))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    getAccessibleContext().setAccessibleDescription("Ventana de acceso a la aplicación");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtUsuarioActionPerformed

  private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnIngresarActionPerformed

  private void btnVisibilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisibilidadMouseClicked
    
  }//GEN-LAST:event_btnVisibilidadMouseClicked

  private boolean Visibilidad(){
    boolean estado = false;
    if (txtContrasenia.getEchoChar()==(char) 0) {
      estado = true;
    } else if (txtContrasenia.getEchoChar()=='*') {
      estado = false;
    }
    return estado;
  }
  
  private void btnVisibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisibilidadActionPerformed
    
  }//GEN-LAST:event_btnVisibilidadActionPerformed

  private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        
  }//GEN-LAST:event_txtContraseniaActionPerformed



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel PanelLogin;
  private java.awt.Button btnIngresar;
  private javax.swing.JToggleButton btnVisibilidad;
  private javax.swing.JLabel etiContrasenia;
  private javax.swing.JLabel etiEncabezado;
  private javax.swing.JLabel etiUsuario;
  private javax.swing.JPasswordField txtContrasenia;
  private javax.swing.JTextField txtUsuario;
  // End of variables declaration//GEN-END:variables
}
